apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-listen-storage-queue.fullname" . }}
  labels:
    {{- include "python-listen-storage-queue.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "python-listen-storage-queue.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "python-listen-storage-queue.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "python-listen-storage-queue.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: azurefileshare
              mountPath: /mnt/azure
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: {{ .Values.azureStorageConnectionString }}
            - name: AZURE_STORAGE_QUEUE_NAME
              value: {{ .Values.azureStorageQueueName }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - ls
            # httpGet:
            #   path: /health
            #   port: http
          readinessProbe:
            exec:
              command:
              - ls
            # httpGet:
            #   path: /health
            #   port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: azurefileshare
          persistentVolumeClaim:
            claimName: fileshare-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
