apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: '{{ template "python-listen-storage-queue.fullname" . }}-scaler'
spec:
  scaleTargetRef:
    name: {{ template "python-listen-storage-queue.fullname" . }}
  minReplicaCount: {{ .Values.kedascaler.minReplicaCount }}
  maxReplicaCount: {{ .Values.kedascaler.maxReplicaCount }}
  pollingInterval: {{ .Values.kedascaler.pollingInterval }}
  cooldownPeriod: {{ .Values.kedascaler.cooldownPeriod }}
  triggers:
  - type: azure-queue
    metadata:
      accountName: "{{ .Values.kedascaler.accountName }}"
      queueName: "{{ .Values.kedascaler.queueName }}"
      queueLength: "{{ .Values.kedascaler.queueLength }}"
      connectionFromEnv: "{{ .Values.kedascaler.connectionFromEnv }}"
