name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
    
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - run: |
          docker build . -t ${{ secrets.ACR_SERVER }}/python-listen-storage-queue:${{ github.sha }}
          docker push ${{ secrets.ACR_SERVER }}/python-listen-storage-queue:${{ github.sha }}

